// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorErrores.Data;

#nullable disable

namespace MonitorErrores.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828024126_AddDiagnosticos")]
    partial class AddDiagnosticos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MonitorErrores.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErroresRecientes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsConocido")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsRecurrente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaDiagnostico")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelGravedad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("MonitorErrores.Models.Error", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Errores");
                });
#pragma warning restore 612, 618
        }
    }
}
